### ISSUE TITLE
How to reproduce the TH04 Kurumi fight crash (mentioned in your latest blog posting)

### ISSUE THREAD

**Issue by colinhowell** [nmlgc/rec98.nmlgc.net#2]
This isn't really an "issue", but rather a comment on your 2022-03-27 blog posting. In that posting, you explain the cause of the Marisa fight crash in TH04 and then mention, "But what's the cause for Kurumi then?" Well, if it helps, I think I know how to reliably reproduce the crash, through a tiny bit of very careful tweaking with Cheat Engine.

When running on Easy (either as Reimu or Marisa, the player makes no difference), if the value of the hidden internal "rank" byte is reduced to 4, which appears to be the minimum achievable rank value for Easy, the Kurumi fight seems to crash reliably. This always happens during her third attack phase (the one in which the side explosion bursts are repeated three times) when she chooses to fire explosions from both sides simultaneously. (There's a chance that she will never fire simultaneous explosions from both sides in this phase, in which case the crash will be avoided, but that seems to be quite unlikely in general.) This crash does not happen if "rank" is greater than 4; even raising it to 5 avoids the crash. So someone playing on Easy who had died a lot or otherwise got their rank lowered to the minimum just before or during Kurumi would be very likely to encounter this crash.

I reproduced this with the English-patched version of TH04, running under DOSBox-X, with Cheat Engine monitoring the DOSBox-X process. My Cheat Engine tweaks in reproducing this were two: 1) "freezing" TH04's invulnerability timer byte to a high value (190), so that I could not be hit, and "freezing" TH04's rank byte to 4, so that rank would remain constant. ("Freezing" in this context means that Cheat Engine monitors the process several times per second and constantly resets the value of the "frozen" location.) Everything else was left alone.

**Comment by nmlgc** [comment]
Thank you very much! That made it trivial to track down the cause, and I've already got a possible fix. I've also found Marisa's crash in the meantime, and there'll be a special blog post very soon.

**Comment by colinhowell** [comment]
Glad that I could be of some help!

**Comment by nmlgc** [comment]
That took quite a bit longer thanks to the complexity of Marisa's Divide Error crash, but it's out now: 

https://rec98.nmlgc.net/blog/2022-04-18
