### ISSUE TITLE
[order.html] Order form is cut off

### ISSUE THREAD

**Issue by Lmocinemod** [nmlgc/rec98.nmlgc.net#3]
On the Order page, the information section regarding TH01 is cut off with an error:
```
template: order.html:95:6: executing "order.html" at : wrong number of args for Blog_PostLink: want 2 got 1
```
The rest of the order form does not render, making it unsubmittable.

The bug appears to be on [line 95](https://github.com/nmlgc/rec98.nmlgc.net/blob/06618d1ae19c67ba94e4bc682fc921f903043070/order.html#L95), introduced in [06618d1](https://github.com/nmlgc/rec98.nmlgc.net/commit/06618d1ae19c67ba94e4bc682fc921f903043070):
```
				{{Blog_PostLink "See the 2022-07-17 blog post for details and an example."}}</p>
```

**Comment by nmlgc** [comment]
Ahh, how embarrassing. Yanga also told me on Twitter, which I saw before this pull request – but yes, that was the correct fix (see 1113b2fece6bec3d88afe8b3806ca3db389e4682). Thank you as well! 👍
